In [1]:
from ioMicro import *

import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_folder = r'D:\241207_WTC11_SFv7_HMERFISH_Analysis'

In [58]:
spots = np.load(data_folder+'\decodedNew_Conv_zscan1_000--.npz', allow_pickle=True)

In [32]:
spots.keys()

KeysView(NpzFile 'D:\\241207_WTC11_SFv7_HMERFISH_Analysis\\decodedNew_Conv_zscan1_000--.npz' with keys: XH_pruned, icodesN, gns_names, dist_best)

In [14]:
spots['XH_pruned'].shape

(2113621, 6, 10)

In [19]:
spots['icodesN']

array([321,  42,  48, ..., 299, 299, 299], dtype=int64)

In [21]:
spots['gns_names']

array(['CRE001', 'CRE002', 'CRE003', 'CRE004', 'CRE005', 'CRE006',
       'CRE007', 'CRE008', 'CRE009', 'CRE010', 'CRE011', 'CRE012',
       'CRE013', 'CRE014', 'CRE015', 'CRE016', 'CRE017', 'CRE018',
       'CRE019', 'CRE020', 'CRE021', 'CRE022', 'CRE023', 'CRE024',
       'CRE025', 'CRE026', 'CRE027', 'CRE028', 'CRE029', 'CRE030',
       'CRE031', 'CRE032', 'CRE033', 'CRE034', 'CRE035', 'CRE036',
       'CRE037', 'CRE038', 'CRE039', 'CRE040', 'CRE041', 'CRE042',
       'CRE043', 'CRE044', 'CRE045', 'CRE046', 'CRE047', 'CRE048',
       'CRE049', 'CRE050', 'CRE051', 'CRE052', 'CRE053', 'CRE054',
       'CRE055', 'CRE056', 'CRE057', 'CRE058', 'CRE059', 'CRE060',
       'CRE061', 'CRE062', 'CRE063', 'CRE064', 'CRE065', 'CRE066',
       'CRE067', 'CRE068', 'CRE069', 'CRE070', 'CRE071', 'CRE072',
       'CRE073', 'CRE074', 'CRE075', 'CRE076', 'CRE077', 'CRE078',
       'CRE079', 'CRE080', 'CRE081', 'CRE082', 'CRE083', 'CRE084',
       'CRE085', 'CRE086', 'CRE087', 'CRE088', 'CRE089', 'CRE0

In [22]:
?get_score_withRef

Signature:
get_score_withRef(
    dec,
    scoresRef,
    plt_val=False,
    gene=None,
    iSs=None,
    th_min=-inf,
)
Docstring: <no docstring>
File:      c:\users\zgibbs\cellpose\iomicro.py
Type:      function

In [57]:
get_score_per_color(dec)

AttributeError: 'dict' object has no attribute 'XH_pruned'

In [78]:
??get_score_per_color

Signature: get_score_per_color(dec)
Docstring: <no docstring>
Source:   
def get_score_per_color(dec):
    H = np.median(dec.XH_pruned[...,-3],axis=1)
    D = dec.XH_pruned[...,:3]-np.mean(dec.XH_pruned[...,:3],axis=1)[:,np.newaxis]
    D = np.mean(np.linalg.norm(D,axis=-1),axis=-1)
    score = np.array([H,-D]).T
    score = np.sort(score,axis=0)
    return [score[dec.XH_pruned[:,0,-2]==icol] for icol in np.arange(dec.ncols)]
File:      c:\users\zgibbs\cellpose\iomicro.py
Type:      function

In [56]:
dec = spots

In [39]:
dec.XH_pruned

AttributeError: 'numpy.ndarray' object has no attribute 'XH_pruned'

In [59]:
spots = dict(spots)

In [60]:
spots.XH_pruned

AttributeError: 'dict' object has no attribute 'XH_pruned'

In [61]:
spots.keys()

dict_keys(['XH_pruned', 'icodesN', 'gns_names', 'dist_best'])

In [62]:
spots_ = np.array(spots)

In [64]:
spots_.XH_pruned

AttributeError: 'numpy.ndarray' object has no attribute 'XH_pruned'

In [79]:
save_folder=r'D:\241207_WTC11_SFv7_HMERFISH_Analysis'#
#r'\\192.168.0.15\cherry2\Zane\300CRE_Schizo_withT7_AdamRNA_WTC11__10_19_2024_HMERFISH_AnalysisGFP'
ifov = 100
fov = 'Conv_zscan1_'+str(ifov).zfill(3)
dec = decoder_simple(save_folder,fov,set_='')

In [80]:
dec.ncols = 3
dec.load_decoded()
dec.dist_best=np.load(dec.decoded_fl)['dist_best']

Loaded decoded: -2.633999824523926


In [82]:
??dec.load_decoded

Signature: dec.load_decoded()
Docstring: <no docstring>
Source:   
    def load_decoded(self):
        import time
        start= time.time()
        self.decoded_fl = self.save_folder+os.sep+'decodedNew_'+self.fov.split('.')[0]+'--'+self.set_+'.npz'
        if not os.path.exists(self.decoded_fl):
            self.decoded_fl = self.save_folder+os.sep+'decoded_'+self.fov.split('.')[0]+'--'+self.set_+'.npz'
        if os.path.exists(self.decoded_fl):
            self.XH_pruned = np.load(self.decoded_fl)['XH_pruned']
            self.icodesN = np.load(self.decoded_fl)['icodesN']
            self.gns_names = np.load(self.decoded_fl)['gns_names']
            print("Loaded decoded:",start-time.time())
            return True
        else:
            return False
File:      c:\users\zgibbs\cellpose\iomicro.py
Type:      method

In [84]:
??get_score_per_color

Signature: get_score_per_color(dec)
Docstring: <no docstring>
Source:   
def get_score_per_color(dec):
    H = np.median(dec.XH_pruned[...,-3],axis=1)
    D = dec.XH_pruned[...,:3]-np.mean(dec.XH_pruned[...,:3],axis=1)[:,np.newaxis]
    D = np.mean(np.linalg.norm(D,axis=-1),axis=-1)
    score = np.array([H,-D]).T
    score = np.sort(score,axis=0)
    return [score[dec.XH_pruned[:,0,-2]==icol] for icol in np.arange(dec.ncols)]
File:      c:\users\zgibbs\cellpose\iomicro.py
Type:      function

In [92]:
dec.drift_fl 

'D:\\241207_WTC11_SFv7_HMERFISH_Analysis\\driftNew_Conv_zscan1_100--.pkl'

In [95]:
np.load(dec.drift_fl, allow_pickle = True)

[[[array([ -0.6012072, -15.794516 ,  -7.1039243], dtype=float32),
   array([ 0.5947494, 15.829344 ,  7.1416926], dtype=float32),
   array([ 0.61422205, 15.724324  ,  7.0278077 ], dtype=float32),
   262,
   130],
  [array([ 5.493981, 17.547733, 20.924192], dtype=float32),
   array([ -5.493981, -17.547733, -20.924192], dtype=float32),
   array([ -8.336562, -17.807676, -20.980482], dtype=float32),
   37,
   27],
  [array([ 0.10505193,  5.72758   , 11.438527  ], dtype=float32),
   array([ -0.09943758,  -5.711954  , -11.465035  ], dtype=float32),
   array([ -0.11781549,  -5.7631035 , -11.378263  ], dtype=float32),
   316,
   139],
  [array([0.05868546, 0.94497895, 5.6295676 ], dtype=float32),
   array([-0.0364834, -0.9409471, -5.6276083], dtype=float32),
   array([-0.10758804, -0.9538595 , -5.633883  ], dtype=float32),
   337,
   153],
  [array([0.06276658, 3.9556212 , 3.8728373 ], dtype=float32),
   array([-0.06935018, -3.92371   , -3.8679333 ], dtype=float32),
   array([-0.0478975, -4.027

In [85]:
scoresRef = get_score_per_color(dec)

In [88]:
len(scoresRef[0])

68614

In [71]:
save_folder=r'D:\241207_WTC11_SFv7_HMERFISH_Analysis'#
#r'\\192.168.0.15\cherry2\Zane\300CRE_Schizo_withT7_AdamRNA_WTC11__10_19_2024_HMERFISH_AnalysisGFP'
ifov = 100
fov = 'Conv_zscan1_'+str(ifov).zfill(3)
#save_folder =r'\\merfish19\merfish19\20240422_R136BICAN2kgene\MERFISHPlate3_4\AnalysisBB_P34_bkremove'
#save_folder =r'R:\Roy\2000gnMERFISH_DCBB_5_9_2024\MERFISH_AnalysisP5P6'
save_fl_ref = r'D:\241207_WTC11_SFv7_HMERFISH_Analysis\scores_ref.pkl'
dec = decoder_simple(save_folder,fov,set_='')
dec.ncols = 3
dec.load_decoded()
dec.dist_best=np.load(dec.decoded_fl)['dist_best']
if False:
    scoresRef = get_score_per_color(dec,include_dbits=True)
    pickle.dump(scoresRef,open(r'D:\241207_WTC11_SFv7_HMERFISH_Analysis\scoresRef.pkl','wb'))
else:
    scoresRef = pickle.load(open(r'D:\241207_WTC11_SFv7_HMERFISH_Analysis\scoresRef.pkl','rb'))
get_score_withRef(dec,scoresRef,plt_val=True,gene=None,iSs = None,th_min=-7.5,include_dbits=True)

gfp_signal_col0 = save_folder+os.sep+dec.fov+r'--H17_MER--col0__Xhfits.npz'
gfp_signal_col1 = save_folder+os.sep+dec.fov+r'--H17_MER--col1__Xhfits.npz'
Xh0 = np.load(gfp_signal_col0)['Xh']
Xh1 = np.load(gfp_signal_col1)['Xh']

Xh0_ = Xh0[(Xh0[:,-2]>0.6)&(Xh0[:,-1]>np.exp(9.5))]### Threshild based on quality of spot
Xh1_ = Xh1[(Xh1[:,-2]>0.6)&(Xh1[:,-1]>np.exp(9.5))]
X0 = Xh0_[:,:3]
X1 = Xh1_[:,:3]
from scipy.spatial import KDTree
dists,inds = KDTree(X0).query(X1)
X1F = Xh1_[(dists<2)][:,[0,1,2,-1]]
if False:
    plt.hist(np.log(Xh0_[:,-1]),density=True,bins=30)
    plt.hist(np.log(Xh0_[inds[(dists<2)],-1]),density=True,bins=30,alpha=0.5)
    plt.hist(np.log(Xh1_[:,-1]),density=True,bins=30)
    plt.hist(np.log(Xh1_[dists<1.5,-1]),density=True,bins=30,alpha=0.5)
if False:
    imGFP = read_im(r'D:\241207_WTC11_SFv7\H17_MER'+os.sep+dec.fov)
    import napari
    V = napari.view_image(imGFP)
    V.add_points(X1F[:,:3],face_color=[0,0,0,0],edge_color='r')
### apply drift
drifts,flds,fov_,fl_ref = np.load(dec.drift_fl,allow_pickle=True)
from worker_ZaneWTC_H import *
fl = r'D:\241207_WTC11_SFv7\H17_MER'+os.sep+dec.fov
drift = get_best_translation_pointsV2(fl,fl_ref,save_folder,'',resc=5)
X1FD = X1F.copy()
X1FD[:,:3]=X1F[:,:3]+drift[0]

X_MERFISH = np.nanmean(dec.XH_pruned[:,:,:3],axis=1)
tree = KDTree(X_MERFISH)
dist,indMER = tree.query(X1FD[:,:3],workers=10)

keepMER = indMER[dist<2]

XH_pruned = dec.XH_pruned[keepMER]
scoreA = dec.scoreA[keepMER]
icodesN = dec.icodesN[keepMER]
ibad = [ign for ign,gn in enumerate(dec.gns_names) if 'blank' in gn]
isbad = np.in1d(icodesN,ibad)
isgood=~isbad

plt.hist(scoreA[isbad],density=True,bins=100)
plt.hist(scoreA[isgood],density=True,bins=100,alpha=0.7);

th=-2
np.sum(dec.scoreA>th),np.sum(scoreA>th)
X1FD.shape,scoreA.shape
print("Fraction of GFP decoded above confidence:",np.sum(scoreA>th)/len(X1FD))#,len(scoreA)/len(X1FD)

XH_prunedf = XH_pruned[scoreA>th]
scoreAf = scoreA[scoreA>th]
icodesNf = icodesN[scoreA>th]
dist_bestf = dec.dist_best[keepMER][scoreA>th]
bigSpot = X1FD[dist<2][scoreA>th][:,-1]>np.exp(12)
#XH_prunedf = XH_pruned[scoreA>th]

_,cts = np.unique(list(icodesNf)+list(np.arange(len(dec.gns_names))),return_counts=True)
cts = cts-1
plt.figure()
plt.plot(ibad,cts[ibad])
igood = np.setdiff1d(np.arange(len(cts)),ibad)
plt.plot(igood,cts[igood])
plt.title(np.round(np.mean(cts[ibad])/np.mean(cts[igood]),2))

Loaded decoded: -2.6650004386901855


FileNotFoundError: [Errno 2] No such file or directory: 'D:\\241207_WTC11_SFv7_HMERFISH_Analysis\\scoresRef.pkl'

In [72]:
save_folder=r'D:\241207_WTC11_SFv7_HMERFISH_Analysis'
ifov = 30
fov = 'Conv_zscan1_'+str(ifov).zfill(3)
#save_folder =r'\\merfish19\merfish19\20240422_R136BICAN2kgene\MERFISHPlate3_4\AnalysisBB_P34_bkremove'
#save_folder =r'R:\Roy\2000gnMERFISH_DCBB_5_9_2024\MERFISH_AnalysisP5P6'
save_fl_ref = r'D:\241207_WTC11_SFv7_HMERFISH_Analysis\scores_ref.pkl'
dec = decoder_simple(save_folder,fov,set_='')
dec.ncols = 1
dec.load_decoded()
dec.dist_best=np.load(dec.decoded_fl)['dist_best']

Loaded decoded: -3.2029802799224854


In [74]:
scoresRef = get_score_per_color(dec)

In [75]:
get_score_withRef(dec,scoresRef,plt_val=True,gene=None,iSs = None,th_min=-7.5,include_dbits=True)

TypeError: get_score_withRef() got an unexpected keyword argument 'include_dbits'