In [1]:
%gui qt5
import napari

In [2]:
from ioMicro import read_im
import numpy as np

In [3]:
# open napari
viewer = napari.Viewer()

In [4]:
# read image and load into napari
img = read_im(r'Z:\Zane_20CRE\7_17_2024__T7_20CRE\HGFP\Conv_zscan__150.zarr')
viewer.add_image(img)

<Image layer 'img' at 0x1c319172bb0>

In [5]:
# load the drift dictionary for a specific FOV
drifts = np.load(r'Z:\Zane_20CRE\7_17_2024__T7_20CRE\drifts_polyA\Conv_zscan__150_drift.pkl', allow_pickle=True)

In [15]:
# load thresholds for T7 data
import numpy as np
h_ths = np.load('final_parms_ths.npz')['final_parms']
h_ths = h_ths.astype(int)

Cannot find steve


In [8]:
h_ths

array([[   1,    0,  612],
       [   1,    1, 1151],
       [   1,    2,  950],
       [   2,    0,  810],
       [   2,    1,  723],
       [   2,    2,  561],
       [   3,    0, 1097],
       [   3,    1, 1081],
       [   3,    2,  613],
       [   4,    0,  806],
       [   4,    1,  255],
       [   4,    2,  591],
       [   5,    0, 1319],
       [   5,    1,  730],
       [   5,    2,  561],
       [   6,    0,  980],
       [   6,    1, 1643],
       [   6,    2,  828],
       [   7,    0,  855],
       [   7,    1, 1333],
       [   7,    2,  107]])

In [13]:
# load spots for a specific enhancer, correct for drift, and add spots (filtered by brightness) to the napari viewer
CRE = np.load(r'Z:\Zane_20CRE\7_17_2024__T7_20CRE\analysis\Conv_zscan__150--H1_fits_icol2.npz')['Xh']
CRE_drift = drifts['H1'][0]
CRE[:,:3]-=CRE_drift
h = CRE[:,7]
keep = np.where((h>150) & (h<5000))
CRE_ = CRE[keep]
viewer.add_points(CRE_[:,:3], size=8, face_color='r', blending='additive')

<Points layer 'Points' at 0x1c320df4e80>

In [14]:
# load spots for a specific T7 transcript, correct for drift, and add spots (filtered by brightness) to the napari viewer
T7 = np.load(r'Z:\Zane_20CRE\7_17_2024__T7_20CRE\analysis\Conv_zscan__150--D1_fits_icol2.npz')['Xh']
T7_drift = drifts['D1'][0]
T7[:,:3]-=T7_drift
h = T7[:,7]
keep = np.where(h > 950)
T7_ = T7[keep]
viewer.add_points(T7_[:,:3], size=8, face_color='green', blending='additive')

<Points layer 'Points [1]' at 0x1c320c8c7f0>

In [43]:
drifts.keys()

dict_keys(['HGFP', 'H0', 'H1', 'D1', 'H2', 'D2', 'H3', 'D3', 'H4', 'D4', 'H5', 'D5', 'H6', 'D6', 'H7', 'D7'])

In [63]:
drifts

{'HGFP': [array([0, 0, 0]),
  [array([0, 0, 0], dtype=int64),
   array([0, 0, 0], dtype=int64),
   array([0, 0, 0], dtype=int64),
   array([0, 0, 0], dtype=int64),
   array([0, 0, 0], dtype=int64)]],
 'H0': [array([  0,  -1, -21]),
  [array([  0,   0, -21], dtype=int64),
   array([  0,  -1, -21], dtype=int64),
   array([  0,  -1, -21], dtype=int64),
   array([  0,   0, -21], dtype=int64),
   array([  0,  -1, -21], dtype=int64)]],
 'H1': [array([  0, -35, 127]),
  [array([  0, -34, 127], dtype=int64),
   array([  0, -35, 127], dtype=int64),
   array([  0, -36, 127], dtype=int64),
   array([  0, -38, 126], dtype=int64),
   array([  0, -34, 129], dtype=int64)]],
 'D1': [array([  1,  -3, -31]),
  [array([  2,  -2, -31], dtype=int64),
   array([  1,  -3, -31], dtype=int64),
   array([  1,  -3, -30], dtype=int64),
   array([  1,  -3, -31], dtype=int64),
   array([  1,  -2, -29], dtype=int64)]],
 'H2': [array([  0,   5, -15]),
  [array([  0,   5, -15], dtype=int64),
   array([  0,   5, -15], 